name: Deploy to CPanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to CPanel
        uses: sebastianroming/cpanel-deploy-action@v1
        with:
         server:  ${{ secrets.ftp_server }}
         username:  ${{ secrets.ftp_username }}
         password: ${{ secrets.ftp_password }}
         directory: /public_html
         exclude: "*.git*"

