name: Deploy to cPanel

on:
  push:
    branches:
      - main # or the branch you want to deploy

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server:  ${{ secrets.ftp_server }}
        username:  ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        state-name: ftp-deploy-sync-state.json
        dry-run: true
